export const categories = [
  {
    name: "Aspiradora",
    items: "60 items",
    img: "/img/aspiradoras de mano.png",
  },
  { name: "Audifonos", items: "12 items", img: "/img/audifonos.png" },
  { name: "Calcetines", items: "12 items", img: "/img/calcetines.png" },
  {
    name: "Cascos de Seguridad",
    items: "12 items",
    img: "/img/cascos de seguridad.png",
  },
  {
    name: "Correas para Perros",
    items: "12 items",
    img: "/img/correas de perros.png",
  },
  { name: "Cuadernos", items: "12 items", img: "/img/cuadernos.png" },
  {
    name: "Detergente",
    items: "60 items",
    img: "/img/detergente.png",
  },
  { name: "Juguetes", items: "12 items", img: "/img/juguetes.png" },
  { name: "Martillos", items: "12 items", img: "/img/martillos.png" },
  {
    name: "Paletas de Sombras",
    items: "12 items",
    img: "/img/paletas de sombras.png",
  },
  { name: "Pulceras", items: "12 items", img: "/img/pulceras.png" },
  { name: "Sartenes", items: "12 items", img: "/img/sartenes.png" },
  { name: "Tiras Led", items: "12 items", img: "/img/tiras led.png" },
  { name: "Toallas", items: "12 items", img: "/img/toallas.png" },
  { name: "Tuppers", items: "12 items", img: "/img/tuppers.png" },
];

export const products = [
  {
    id: 1,
    title: "Aspiradora",
    price: "$49.99",
    img: "/img/aspiradoras de mano.png",
    category: "Aspiradora",
    description:
      "Aspiradora portátil ideal para limpieza rápida en casa y auto.",
    gallery: [
      "/img/aspiradoras de mano.png",
      "/img/aspiradoras de mano.png",
      "/img/aspiradoras de mano.png",
    ],
    specs: ["Portátil", "Batería 12h", "Silenciosa"],
  },
  {
    id: 2,
    title: "Audifonos",
    price: "$29.99",
    img: "/img/audifonos.png",
    category: "Audifonos",
    description: "Audífonos con sonido envolvente y micrófono integrado.",
    gallery: ["/img/audifonos.png", "/img/audifonos.png", "/img/audifonos.png"],
    specs: ["Bluetooth", "Cancelación de ruido", "20h batería"],
  },
  {
    id: 3,
    title: "Calcetines",
    price: "$12.99",
    img: "/img/calcetines.png",
    category: "Calcetines",
    description:
      "Pack de calcetines de algodón premium, suaves y transpirables.",
    gallery: [
      "/img/calcetines.png",
      "/img/calcetines.png",
      "/img/calcetines.png",
    ],
    specs: ["100% Algodón", "Talla única", "Pack x3"],
  },
  {
    id: 4,
    title: "Cascos de seguridad",
    price: "$35.50",
    img: "/img/cascos de seguridad.png",
    category: "Cascos de seguridad",
    description:
      "Casco industrial de alta resistencia con suspensión ajustable.",
    gallery: [
      "/img/cascos de seguridad.png",
      "/img/cascos de seguridad.png",
      "/img/cascos de seguridad.png",
    ],
    specs: ["Norma ANSI", "Ajuste tipo matrac", "Resistente a impactos"],
  },
  {
    id: 5,
    title: "Correas para perros",
    price: "$15.00",
    img: "/img/correas de perros.png",
    category: "Correas para perros",
    description:
      "Correa extensible y resistente para paseos seguros con tu mascota.",
    gallery: [
      "/img/correas de perros.png",
      "/img/correas de perros.png",
      "/img/correas de perros.png",
    ],
    specs: ["5 metros", "Nylon reforzado", "Agarre ergonómico"],
  },
  {
    id: 6,
    title: "Cuadernos",
    price: "$8.99",
    img: "/img/cuadernos.png",
    category: "Cuadernos",
    description: "Cuaderno de pasta dura con hojas de raya de alto gramaje.",
    gallery: ["/img/cuadernos.png", "/img/cuadernos.png", "/img/cuadernos.png"],
    specs: ["100 hojas", "Papel ecológico", "Pasta dura"],
  },
  {
    id: 7,
    title: "Detergente",
    price: "$18.50",
    img: "/img/detergente.png",
    category: "Detergente",
    description:
      "Detergente líquido concentrado con aroma frescura de montaña.",
    gallery: [
      "/img/detergente.png",
      "/img/detergente.png",
      "/img/detergente.png",
    ],
    specs: ["Biodegradable", "3 Litros", "Quita manchas"],
  },
  {
    id: 8,
    title: "Juguetes",
    price: "$24.99",
    img: "/img/juguetes.png",
    category: "Juguetes",
    description: "Set de figuras de acción articuladas para niños de 3+ años.",
    gallery: ["/img/juguetes.png", "/img/juguetes.png", "/img/juguetes.png"],
    specs: ["Libre de BPA", "Didáctico", "Multicolor"],
  },
  {
    id: 9,
    title: "Martillos",
    price: "$14.99",
    img: "/img/martillos.png",
    category: "Martillos",
    description: "Martillo de uña de acero forjado con mango antideslizante.",
    gallery: ["/img/martillos.png", "/img/martillos.png", "/img/martillos.png"],
    specs: ["Acero Forjado", "Mango Fibra", "16 oz"],
  },
  {
    id: 10,
    title: "Paletas de sombras",
    price: "$32.00",
    img: "/img/paletas de sombras.png",
    category: "Paletas de sombras",
    description: "Paleta con 12 tonos mate y brillantes de alta pigmentación.",
    gallery: [
      "/img/paletas de sombras.png",
      "/img/paletas de sombras.png",
      "/img/paletas de sombras.png",
    ],
    specs: ["Cruelty Free", "Larga duración", "Espejo integrado"],
  },
  {
    id: 11,
    title: "Pulceras",
    price: "$19.99",
    img: "/img/pulceras.png",
    category: "Pulceras",
    description: "Pulsera de plata elegante con dije ajustable.",
    gallery: ["/img/pulceras.png", "/img/pulceras.png", "/img/pulceras.png"],
    specs: ["Plata .925", "Ajustable", "Estuche incluido"],
  },
  {
    id: 12,
    title: "Sartenes",
    price: "$55.00",
    img: "/img/sartenes.png",
    category: "Sartenes",
    description: "Sartén antiadherente de cerámica compatible con inducción.",
    gallery: ["/img/sartenes.png", "/img/sartenes.png", "/img/sartenes.png"],
    specs: ["PFOA Free", "24cm diámetro", "Fácil limpieza"],
  },
  {
    id: 13,
    title: "Tiras Led",
    price: "$22.50",
    img: "/img/tiras led.png",
    category: "Tiras Led",
    description: "Tiras LED RGB con control remoto y sincronización de música.",
    gallery: ["/img/tiras led.png", "/img/tiras led.png", "/img/tiras led.png"],
    specs: ["5 metros", "Control remoto", "RGB 16 colores"],
  },
  {
    id: 14,
    title: "Toallas",
    price: "$28.00",
    img: "/img/toallas.png",
    category: "Toallas",
    description:
      "Juego de toallas de baño de lujo, ultra absorbentes y suaves.",
    gallery: ["/img/toallas.png", "/img/toallas.png", "/img/toallas.png"],
    specs: ["Algodón egipcio", "700 GSM", "Secado rápido"],
  },
  {
    id: 15,
    title: "Tuppers",
    price: "$20.99",
    img: "/img/tuppers.png",
    category: "Tuppers",
    description: "Set de recipientes herméticos para almacenamiento de comida.",
    gallery: ["/img/tuppers.png", "/img/tuppers.png", "/img/tuppers.png"],
    specs: ["Apto microondas", "Hermético", "Set de 5 piezas"],
  },
];
